### ISSUE TITLE
Set up pre-commit yaml

### ISSUE THREAD

**Issue by SaranjeetKaur** [imperialCHEPI/healthgpsrvis#6]
- Use `lintr` and also set up `pre-commit` yaml file.
- Update `.gitignore` template
- Generate `README.Rmd` and convert it to `README.md` before commiting

**Comment by alexdewar** [comment]
I just came on here to post this because I noticed the pre-commit CI app was failing. Bigger picture, it's my fault for enabling it for every repo on the org unconditionally, but if you're going to use pre-commit anyway then that'll also fix things :smile: 

Do you think I should disable it for new repos @jamesturner246? I mean, we don't have many repos on here and most of them do use pre-commit, but...

**Comment by SaranjeetKaur** [comment]
Hi @alexdewar, I am planning to include pre-commit on this repo. I would have done that by now but I am running into some errors and will be catching up with James shortly today to work on it

**Comment by SaranjeetKaur** [comment]
Steps to autogenerate `.pre-commit-config.yaml` in RStudio on Windows:
-  `pip install pre-commit --user` (macOS, Linux and Windows) outside a conda or virtual environment.
- `install.packages("precommit") on RStudio console
- check whether the path to the pre-commit executable is available on RStudio using `precommit::path_precommit_exec()`
- If the pre-commit executable is not discoverable, then find its location on your local machine and set it for RStudio as follows:

1. `precommit_path <- "C:/Users/ssbhogal/.pyenv/pyenv-win/versions/3.11.0/Scripts/pre-commit.exe" # path to the pre-commit executable`
2.  `options(precommit.executable = precommit_path)  # set R options`
3. `getOption("precommit.executable")` should return the path to the executable, if everything is ok. In this case, it will return `"C:/Users/ssbhogal/.pyenv/pyenv-win/versions/3.11.0/Scripts/pre-commit.exe"`. The same output will also be returned if instead you use `precommit::path_precommit_exec()`.
4. use `precommit::use_precommit()` to autogenerate `.pre-commit-config.yaml` 
5.

**Comment by jamesturner246** [comment]
Ideally we will use it in all repos, eventually, but I'm not against changing it if it prevents issues.

**Comment by SaranjeetKaur** [comment]
This can be setup using:

- In RStudio terminal run `pip3 install pre-commit --user`
- In the RStudio console run `install.packages("precommit")` followed by `precommit::use_precommit()` and it will set up the `.pre-commit-config.yml` file which you can then push to the repo
